Sprint2/step2
alex-markin/react-stellar-burger pull request #7
Opened 2023-06-07 20:54 UTC by alex-markin

2023-06-08 18:23 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая организация хранилища
- Редьюсеры - чистые функции
- Хорошая работа с RTK

Необходимо исправить:
- Неправильно работает добавление ингредиентов, если добавить несколько одинаковых ингредиентов, то отображается только один. Для атрибута key в конструкторе нужно использовать для ингредиента уникальный uuid (Вам нужно его генерировать во время сброса в зону DnD). Это можно делать с помощью библиотеки uuid https://www.npmjs.com/package/uuid , или Вам должны были показать, как это сделать, иначе некорректно может работать DND. А в key будет уже просто key={ item.uuid }

<img width="886" alt="Снимок экрана 2023-06-08 в 21 19 17" src="https://github.com/alex-markin/react-stellar-burger/assets/60173362/e7200765-7b4a-4bb9-8b96-084c9339a8d9">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-08 18:23 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const data = useSelector((store) => store.data); // данные с сервера
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-06-08 18:23 UTC, andryxxa93 commented on src/services/ingredients-slice.js
> +    totalPrice: 0,
**Можно лучше**

Хотя в задании и предложено вычислять полную стоимость в редьюсере, но это плохая идея, т.к. общая стоимость это производные данные от данных о бургере и сейчас у нас в некотором роде дублируется эта информация (есть массив ингредиентов с ценами и есть отдельно полная стоимость)

Поэтому лучше рассчитывать их не в редьюсере а просто в компоненте конструктора используя useMemo

```
const totalPrice = useMemo(()=> {
   return **рассчет стоимости**
}, burgersData)
```

так стоимость будет перерасчитываться в момент изменения бургера

2023-06-08 18:23 UTC, andryxxa93 commented on src/services/order-slice.js
> +      state.order = [];
**Можно лучше**
Лучше делать ресет на `null` а не на пустой массив

2023-06-09 11:52 UTC, alex-markin commented on src/services/ingredients-slice.js
> +    totalPrice: 0,
Мне тоже казалось, что так будет сильно удобнее. Исправил, спасибо.

2023-06-09 11:52 UTC, alex-markin commented on src/services/order-slice.js
> +      state.order = [];
Исправил, спасибо.

2023-06-09 15:54 UTC, alex-markin commented on src/components/app/app.jsx
> +  const data = useSelector((store) => store.data); // данные с сервера
Исправил глобально, спасибо за совет.

2023-06-10 07:38 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-10 12:01 UTC, merged