Routing/step1
alex-markin/react-stellar-burger pull request #8
Opened 2023-07-08 10:12 UTC by alex-markin

2023-07-08 10:36 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Защита роутов реализована в одном компоненте
- Есть обновление токена
- Роутинг настроен и работает правильно

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При отправке запроса на код восстановления пользователя редиректит на `reset-password`, но висит лоадер.

<img width="1440" alt="Снимок экрана 2023-07-08 в 13 28 14" src="https://github.com/alex-markin/react-stellar-burger/assets/60173362/e2ea0180-5951-463b-8f0e-e33fc6fc6e77">

- При изменни данных юзера на странице профиля происходит сразу два запроса - patch и get. Последний это лишнее. patch запрос возвращает актуальные данные юзера.

- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".

- Роут конструктора должен быть публичным.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-08 10:36 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        <Route path="/profile" element={<OnlyAuth component={<Profile />} />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-07-08 10:36 UTC, andryxxa93 commented on src/components/ingredient-details/Ingredient-details.jsx
> +  const ingredients = JSON.parse(localStorage.getItem('ingredients'));
**Можно лучше**
При парсинге может случиться ошибка, из-за которой ляжет приложение. Желательно оборачивать в try-catch

2023-07-08 10:47 UTC, alex-markin commented on src/components/app/app.jsx
> +        <Route path="/profile" element={<OnlyAuth component={<Profile />} />} />
Переделал, спасибо.

2023-07-08 11:11 UTC, alex-markin commented on src/components/ingredient-details/Ingredient-details.jsx
> +  const ingredients = JSON.parse(localStorage.getItem('ingredients'));
Исправил, сделал условие, что если происходит ошибка, то навигация уводит на 404 страницу

2023-07-08 11:54 UTC, alex-markin commented
Добрый день. Спасибо за ревью.

При отправке запроса на код восстановления пользователя редиректит на reset-password, но висит лоадер. - **исправил**

При изменни данных юзера на странице профиля происходит сразу два запроса - patch и get. Последний это лишнее. patch запрос возвращает актуальные данные юзера. - **исправил**

В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов". - **исправил**

Роут конструктора должен быть публичным. - **исправил**

2023-07-09 05:55 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-10 16:05 UTC, merged